org: tvqqq
app: sls-fb-manager
service: sls-fb-manager
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  timeout: 30
  environment:
    CONFIG_FAT_ID: ${param:CONFIG_FAT_ID}
    MONGODB_URL: ${param:MONGODB_URL}
    SLACK_WEBHOOK_URL: ${param:SLACK_WEBHOOK_URL}

functions:
  api:
    handler: handler.serverless
    events:
      - httpApi: "*"

  cronFetchList:
    handler: handler.cron
    events:
      - schedule: cron(00 14 * * ? *) # 21h UTC+7 = 14
